version: "3"

services:
  lawyers-db:
    container_name: lawyers-db
    image: mongo:latest
    volumes:
      - "./db-volumes/lawyers:/data/db"
    ports:
      - 27018:27017

  lawyers-service:
    container_name: lawyers-service
    build: ./lawyers/
    volumes:
      - "./lawyers:/usr/src/"
      - "./lawyers/package.json:/usr/src/package.json"
    ports:
      - "3001:3000" # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
    depends_on:
      - lawyers-db
    links:
      - lawyers-db

  doctors-db:
    container_name: doctors-db
    image: mongo:latest
    volumes:
      - "./db-volumes/doctors:/data/db"
    ports:
      - 27019:27017

  doctors-service:
    container_name: doctors-service
    build: ./doctors
    volumes:
      - "./doctors:/usr/src/"
      - "./doctors/package.json:/usr/src/package.json"
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
    depends_on:
      - doctors-db
    links:
      - doctors-db

  web-service:
    container_name: web-service
    build: ./client
    volumes:
      - "./client:/usr/src"
      - "./client/package.json:/usr/src/package.json"
    ports:
      - "3000:3000"
    depends_on:
      - doctors-service
      - lawyers-service
